### ISSUE TITLE
Playback Speed

### ISSUE THREAD

**Issue by hiteshgarg002** [the-meedu-app/flutter-meedu-player#1]
Thanks for this plugin.
Can you please add the functionality of setting playback speed? Would be really great to have that functionality.

**Comment by hiteshgarg002** [comment]
Hey @the-meedu-app any update on this?

**Comment by the-meedu-app** [comment]
> Hey @the-meedu-app any update on this?

hello @hiteshgarg002 I am working in this, soon I will update the plugin

**Comment by the-meedu-app** [comment]
> > Hey @the-meedu-app any update on this?
> 
> hello @hiteshgarg002 I am working in this, soon I will update the plugin

This package use the official video_player plugin, video_player doesn't support playback speed in this moment.

For more info go to https://github.com/flutter/flutter/issues/29900

**Comment by hiteshgarg002** [comment]
Hi,

Please update video_player plugin to version "video_player: ^0.11.0" which now supports playback speed feature.

Thanks.

**Comment by hiteshgarg002** [comment]
> 
> 
> > > Hey @the-meedu-app any update on this?
> > 
> > 
> > hello @hiteshgarg002 I am working in this, soon I will update the plugin
> 
> This package use the official video_player plugin, video_player doesn't support playback speed in this moment.
> 
> For more info go to [flutter/flutter#29900](https://github.com/flutter/flutter/issues/29900)

Hi,

Please update video_player plugin to version "video_player: ^0.11.0" which now supports playback speed feature.

Thanks.

**Comment by the-meedu-app** [comment]
> > > > Hey @the-meedu-app any update on this?
> > > 
> > > 
> > > hello @hiteshgarg002 I am working in this, soon I will update the plugin
> > 
> > 
> > This package use the official video_player plugin, video_player doesn't support playback speed in this moment.
> > For more info go to [flutter/flutter#29900](https://github.com/flutter/flutter/issues/29900)
> 
> Hi,
> 
> Please update video_player plugin to version "video_player: ^0.11.0" which now supports playback speed feature.
> 
> Thanks.

You can check the branch `getx` this is the new version of this library with some breaking changes and now implements the playback speed. The documentation of the new version is still in working.
