### ISSUE TITLE
example contains errors

### ISSUE THREAD

**Issue by shyamganesh-dev** [the-meedu-app/flutter-meedu-player#11]

**Comment by shyamganesh-dev** [comment]
please correct it soon

**Comment by the-meedu-app** [comment]
> please correct it soon

hello. Could you provide more information about the errors?

**Comment by the-meedu-app** [comment]
Please update to the new version 
meedu_player: ^0.2.2

**Comment by shyamganesh-dev** [comment]
Ok thanks bro..no problem after the update
