### ISSUE TITLE
UI for Playback Speed & Video Resolution (Quality)

### ISSUE THREAD

**Issue by hiteshgarg002** [the-meedu-app/flutter-meedu-player#14]
Hi,

Thanks for this great library.

Loved the UI you created. Can you please add Playback speed & Video quality option into player UI?

**Comment by the-meedu-app** [comment]
> Hi,
> 
> Thanks for this great library.
> 
> Loved the UI you created. Can you please add Playback speed & Video quality option into player UI?

For playback speed check the example https://github.com/the-meedu-app/flutter-meedu-player/blob/master/plugin/example/lib/pages/playback_speed_example_page.dart

**Comment by hiteshgarg002** [comment]
Can you please add this along with quality options into player UI?

**Comment by the-meedu-app** [comment]
> Can you please add this along with quality options into player UI?

For quality change check the example https://github.com/the-meedu-app/flutter-meedu-player/blob/master/plugin/example/lib/pages/change_quality_example_page.dart
