### ISSUE TITLE
Problem when using player on 2 consecutive screens

### ISSUE THREAD

**Issue by Omi231** [the-meedu-app/flutter-meedu-player#15]
First of all thanks for this amazing player. Recently i replaced Chewie with Meedu player because I liked this interface/UI. But I am facing one problem with this player. I have a list of routes on each route there is a video. The first route's video plays without any problem but as soon as i do Navigator.pushReplacementNamed() to any route the video player gives error. 

Upon trying to debug i found that dispose() method of previous route is being called late after initState() of new route which means the playerController is being disposed after new route is opened so on new route it gives the red error (screenshot attached below).  For now sadly i need to move back to Chewie because it working fine in this same scenario. Please fix this issue if possible... 

`A VideoPlayerController was used after being disposed`

![image](https://user-images.githubusercontent.com/44071105/95671784-39ff8d00-0bb4-11eb-849f-eba6ae9957e0.png)

_My init method:_

`_init() {
    _meeduPlayerController.setDataSource(
      DataSource(
        type: DataSourceType.network,
        source: optedVideo['video'].toString(),
      ),
      autoplay: true,
    );
  }`

_My dispose method:_

```
void dispose() {   
    _playerEventSubs?.cancel();
    Wakelock.disable();
    _meeduPlayerController.dispose();
    super.dispose();
  }
```

**Comment by the-meedu-app** [comment]
> First of all thanks for this amazing player. Recently i replaced Chewie with Meedu player because I liked this interface/UI. But I am facing one problem with this player. I have a list of routes on each route there is a video. The first route's video plays without any problem but as soon as i do Navigator.pushReplacementNamed() to any route the video player gives error.
> 
> Upon trying to debug i found that dispose() method of previous route is being called late after initState() of new route which means the playerController is being disposed after new route is opened so on new route it gives the red error (screenshot attached below). For now sadly i need to move back to Chewie because it working fine in this same scenario. Please fix this issue if possible...
> 
> `A VideoPlayerController was used after being disposed`
> 
> ![image](https://user-images.githubusercontent.com/44071105/95671784-39ff8d00-0bb4-11eb-849f-eba6ae9957e0.png)
> 
> _My init method:_
> 
> `_init() { _meeduPlayerController.setDataSource( DataSource( type: DataSourceType.network, source: optedVideo['video'].toString(), ), autoplay: true, ); }`
> 
> _My dispose method:_
> 
> ```
> void dispose() {   
>     _playerEventSubs?.cancel();
>     Wakelock.disable();
>     _meeduPlayerController.dispose();
>     super.dispose();
>   }
> ```

Thanks for you feedback. I will try to reproduce the issue, also make sure that each route has an unique MeeduPlayerController and before call Navigator.pushReplacementNamed() you must dispose the MeeduPlayerController like this
```dart



Future<void> videoDispose()async{
  if(_meeduPlayerController!=null){
    _playerEventSubs?.cancel();    
    Wakelock.disable();
    await   _meeduPlayerController.dispose();
   _meeduPlayerController = null;
 }

}

goTo ()async{
 await  this.videoDispose();
Navigator.pushReplacementNamed(context,'your-route);
}

@override
void dispose() {   
    this.videoDispose();
    super.dispose();
 }

```


If you can provide your code to replicate the issue that will be great

**Comment by Omi231** [comment]
> > First of all thanks for this amazing player. Recently i replaced Chewie with Meedu player because I liked this interface/UI. But I am facing one problem with this player. I have a list of routes on each route there is a video. The first route's video plays without any problem but as soon as i do Navigator.pushReplacementNamed() to any route the video player gives error.
> > Upon trying to debug i found that dispose() method of previous route is being called late after initState() of new route which means the playerController is being disposed after new route is opened so on new route it gives the red error (screenshot attached below). For now sadly i need to move back to Chewie because it working fine in this same scenario. Please fix this issue if possible...
> > `A VideoPlayerController was used after being disposed`
> > ![image](https://user-images.githubusercontent.com/44071105/95671784-39ff8d00-0bb4-11eb-849f-eba6ae9957e0.png)
> > _My init method:_
> > `_init() { _meeduPlayerController.setDataSource( DataSource( type: DataSourceType.network, source: optedVideo['video'].toString(), ), autoplay: true, ); }`
> > _My dispose method:_
> > ```
> > void dispose() {   
> >     _playerEventSubs?.cancel();
> >     Wakelock.disable();
> >     _meeduPlayerController.dispose();
> >     super.dispose();
> >   }
> > ```
> 
> Thanks for you feedback. I will try to reproduce the issue, also make sure that each route has an unique MeeduPlayerController and before call Navigator.pushReplacementNamed() you must dispose the MeeduPlayerController like this
> 
> ```dart
> Future<void> videoDispose()async{
>   if(_meeduPlayerController!=null){
>     _playerEventSubs?.cancel();    
>     Wakelock.disable();
>     await   _meeduPlayerController.dispose();
>    _meeduPlayerController = null;
>  }
> 
> }
> 
> goTo ()async{
>  await  this.videoDispose();
> Navigator.pushReplacementNamed(context,'your-route);
> }
> 
> @override
> void dispose() {   
>     this.videoDispose();
>     super.dispose();
>  }
> ```
> 
> If you can provide your code to replicate the issue that will be great

Hi,

I have tried everything including your suggested workaround but it doesn't work. My code is very simple.

`@override
  void initState() {
    super.initState();
    log("new player route opened");
    _getItems(); //Firebase database call

    _playerEventSubs = _meeduPlayerController.onPlayerStatusChanged.listen(
      (PlayerStatus status) {
        if (status == PlayerStatus.playing) {
          Wakelock.enable();
        } else {
          Wakelock.disable();
        }
      },
    );

    WidgetsBinding.instance.addPostFrameCallback((_) {
      _init();
    });
  }

  _init() async {
    await _meeduPlayerController.setDataSource(
      DataSource(
        type: DataSourceType.network,
        source: optedVideo['video'].toString(),
      ),
      autoplay: true,
    );
  }

@override
  void dispose() {
    this.videoDispose();
    super.dispose();
  }
`

The problem seems to be something to do with how MeeduController disposes itself when controller.dispose is called.

 Look at this log, the dispose event is being called late after new screen is opened.
![image](https://user-images.githubusercontent.com/44071105/95784208-d6c54600-0cec-11eb-83a6-51353155c373.png)

**Comment by the-meedu-app** [comment]
> > > First of all thanks for this amazing player. Recently i replaced Chewie with Meedu player because I liked this interface/UI. But I am facing one problem with this player. I have a list of routes on each route there is a video. The first route's video plays without any problem but as soon as i do Navigator.pushReplacementNamed() to any route the video player gives error.
> > > Upon trying to debug i found that dispose() method of previous route is being called late after initState() of new route which means the playerController is being disposed after new route is opened so on new route it gives the red error (screenshot attached below). For now sadly i need to move back to Chewie because it working fine in this same scenario. Please fix this issue if possible...
> > > `A VideoPlayerController was used after being disposed`
> > > ![image](https://user-images.githubusercontent.com/44071105/95671784-39ff8d00-0bb4-11eb-849f-eba6ae9957e0.png)
> > > _My init method:_
> > > `_init() { _meeduPlayerController.setDataSource( DataSource( type: DataSourceType.network, source: optedVideo['video'].toString(), ), autoplay: true, ); }`
> > > _My dispose method:_
> > > ```
> > > void dispose() {   
> > >     _playerEventSubs?.cancel();
> > >     Wakelock.disable();
> > >     _meeduPlayerController.dispose();
> > >     super.dispose();
> > >   }
> > > ```
> > 
> > 
> > Thanks for you feedback. I will try to reproduce the issue, also make sure that each route has an unique MeeduPlayerController and before call Navigator.pushReplacementNamed() you must dispose the MeeduPlayerController like this
> > ```dart
> > Future<void> videoDispose()async{
> >   if(_meeduPlayerController!=null){
> >     _playerEventSubs?.cancel();    
> >     Wakelock.disable();
> >     await   _meeduPlayerController.dispose();
> >    _meeduPlayerController = null;
> >  }
> > 
> > }
> > 
> > goTo ()async{
> >  await  this.videoDispose();
> > Navigator.pushReplacementNamed(context,'your-route);
> > }
> > 
> > @override
> > void dispose() {   
> >     this.videoDispose();
> >     super.dispose();
> >  }
> > ```
> > 
> > 
> > If you can provide your code to replicate the issue that will be great
> 
> Hi,
> 
> I have tried everything including your suggested workaround but it doesn't work. My code is very simple.
> 
> `@override
> void initState() {
> super.initState();
> log("new player route opened");
> _getItems(); //Firebase database call
> 
> ```
> _playerEventSubs = _meeduPlayerController.onPlayerStatusChanged.listen(
>   (PlayerStatus status) {
>     if (status == PlayerStatus.playing) {
>       Wakelock.enable();
>     } else {
>       Wakelock.disable();
>     }
>   },
> );
> 
> WidgetsBinding.instance.addPostFrameCallback((_) {
>   _init();
> });
> ```
> 
> }
> 
> _init() async {
> await _meeduPlayerController.setDataSource(
> DataSource(
> type: DataSourceType.network,
> source: optedVideo['video'].toString(),
> ),
> autoplay: true,
> );
> }
> 
> @override
> void dispose() {
> this.videoDispose();
> super.dispose();
> }
> `
> 
> The problem seems to be something to do with how MeeduController disposes itself when controller.dispose is called.
> 
> Look at this log, the dispose event is being called late after new screen is opened (this happens even after implementing ur suggestion).
> ![image](https://user-images.githubusercontent.com/44071105/95784208-d6c54600-0cec-11eb-83a6-51353155c373.png)

Great thanks please update to `meedu_player: ^3.3.3` and check if the problem persists

**Comment by Omi231** [comment]
Thank you so much the problem is fixed.
