### ISSUE TITLE
I need a idel to create list video!

### ISSUE THREAD

**Issue by gamestap99** [the-meedu-app/flutter-meedu-player#16]
hey master, i want to create a list video and items not auto init. initialization stars when i click item me want. and at a time i want to only video is playing

**Comment by the-meedu-app** [comment]
> hey master, i want to create a list video and items not auto init. initialization stars when i click item me want. and at a time i want to only video is playing

This is not an issue. You can use autoplay false
```dart
 _meeduPlayerController.setDataSource(
      DataSource(
        type: DataSourceType.network,
        source: "https://www.radiantmediaplayer.com/media/big-buck-bunny-360p.mp4",
      ),
      autoplay: false
);
```
