### ISSUE TITLE
Full screen video in portrait mode

### ISSUE THREAD

**Issue by falguni0314** [the-meedu-app/flutter-meedu-player#17]
Hi, I want to play my videos in fullscreen portrait mode, kindly help.

**Comment by the-meedu-app** [comment]
> Hi, I want to play my videos in fullscreen portrait mode, kindly help.

When you create an instance of MeeduPlayerController you can pass the param **screenManager** these must be an instance of ScreenManager and pass the param **forceLandScapeInFullscreen** as false to allow play videos in portrait and landscape mode

**Comment by falguni0314** [comment]
Great!!, Thanks for your response.

is there a way to know when VideoController is initialised and access value(such as aspect ratio, size etc) from it?

**Comment by the-meedu-app** [comment]
> Great!!, Thanks for your response.
> 
> is there a way to know when VideoController is initialised and access value(such as aspect ratio, size etc) from it?

the method **setDataSource** is asynchronous so  you can wait to the finish of this method and after use the get `videoPlayerController` to access to the controller of VideoPlayerController an access to all info provided for the official puglin video_player.


for example
```dart
await meeduPlayerController.setDataSource(...);
if(meeduPlayerController.videoPlayerController.value.initialized){
    meeduPlayerController.videoPlayerController.value.aspectRatio;
}
```

aslo you can use the stream **(onDataStatusChanged)[https://the-meedu-app.github.io/flutter-meedu-player/#/listening-player-events?id=streams]** 

```dart
_playerEventSubs = _meeduPlayerController.onDataStatusChanged.listen(
      (status) {
      if(meeduPlayerController.videoPlayerController.value.initialized){
             meeduPlayerController.videoPlayerController.value.aspectRatio;
        }
      },
    );
```
