### ISSUE TITLE
Issue while playing file video

### ISSUE THREAD

**Issue by falguni0314** [the-meedu-app/flutter-meedu-player#19]
Hi, when I am selecting a file using file picker from device storage, video is not getting played and getting below error.

I/flutter (30722): NoSuchMethodError: The getter 'path' was called on null.
I/flutter (30722): Receiver: null
I/flutter (30722): Tried calling: path
I/flutter (30722): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
I/flutter (30722): #1      new VideoPlayerController.file (package:video_player/video_player.dart:202:37)
I/flutter (30722): #2      MeeduPlayerController._createVideoController (package:meedu_player/src/controller.dart:176:17)
I/flutter (30722): #3      MeeduPlayerController.setDataSource (package:meedu_player/src/controller.dart:261:32)
I/flutter (30722): #4      _AssetPlayer.initVideoPlayer (package:thatslife/app/modules/upload_file/videoPlayerAsset.dart:39:36)
I/flutter (30722): #5      _AssetPlayer.initState.<anonymous closure> (package:thatslife/app/modules/upload_file/videoPlayerAsset.dart:70:18)
I/flutter (30722): #6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
I/flutter (30722): #7      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1063:9)
I/flutter (30722): #8      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
I/flutter (30722): #9      _rootRun (dart:async/zone.dart:1190:13)
I/flutter (30722): #10     _CustomZone.run (dart:async/zone.dart:1093:19)
I/flutter (30722): #11     _CustomZone.runGuarded (dart:async/zone.da

**Comment by the-meedu-app** [comment]
> Hi, when I am selecting a file using file picker from device storage, video is not getting played and getting below error.
> 
> I/flutter (30722): NoSuchMethodError: The getter 'path' was called on null.
> I/flutter (30722): Receiver: null
> I/flutter (30722): Tried calling: path
> I/flutter (30722): #0 Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
> I/flutter (30722): #1 new VideoPlayerController.file (package:video_player/video_player.dart:202:37)
> I/flutter (30722): #2 MeeduPlayerController._createVideoController (package:meedu_player/src/controller.dart:176:17)
> I/flutter (30722): #3 MeeduPlayerController.setDataSource (package:meedu_player/src/controller.dart:261:32)
> I/flutter (30722): #4 _AssetPlayer.initVideoPlayer (package:thatslife/app/modules/upload_file/videoPlayerAsset.dart:39:36)
> I/flutter (30722): #5 _AssetPlayer.initState. (package:thatslife/app/modules/upload_file/videoPlayerAsset.dart:70:18)
> I/flutter (30722): #6 SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
> I/flutter (30722): #7 SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1063:9)
> I/flutter (30722): #8 SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
> I/flutter (30722): #9 _rootRun (dart:async/zone.dart:1190:13)
> I/flutter (30722): #10 _CustomZone.run (dart:async/zone.dart:1093:19)
> I/flutter (30722): #11 _CustomZone.runGuarded (dart:async/zone.da

Thanks for your feedback I will check and Fix it soon

**Comment by the-meedu-app** [comment]
@falguni0314  I've used the [file_picker](https://pub.dev/packages/file_picker) plugin and works fine.

```dart
import 'dart:io';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:meedu_player/meedu_player.dart';

class PickFileExamplePage extends StatefulWidget {
  PickFileExamplePage({Key key}) : super(key: key);

  @override
  _PickFileExamplePageState createState() => _PickFileExamplePageState();
}

class _PickFileExamplePageState extends State<PickFileExamplePage> {
  final _controller = MeeduPlayerController(
    screenManager: ScreenManager(forceLandScapeInFullscreen: false),
  );

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  _onPickFile() async {
    FilePickerResult result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['mov', 'avi', 'mp4'],
    );

    if (result != null) {
      File file = File(result.files.single.path);
      _controller.launchAsFullscreen(
        context,
        autoplay: true,
        dataSource: DataSource(
          file: file,
          type: DataSourceType.file,
        ),
      );
    } else {
      // User canceled the picker
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: FlatButton(
          child: Text("Pick video file"),
          onPressed: this._onPickFile,
        ),
      ),
    );
  }
}
```


Please provide you code to check what is the problem.

**Comment by falguni0314** [comment]
Great!! Thanks for your help, I was doing as below

dataSource: DataSource(
          source: file (as string),
          type: DataSourceType.file,
        )

Now I have changed it to

dataSource: DataSource(
          file: file,
          type: DataSourceType.file,
        )

Now it`s fixed.
