### ISSUE TITLE
Multiple Errors with Live Video

### ISSUE THREAD

**Issue by CarmenLexa** [the-meedu-app/flutter-meedu-player#20]
I am playing live videos, at first it works very well but when changing video I have these errors:

//THE VIDEO PLAYS AND THEN PAUSES AND A RED COLOR BLOCK APPEARS THAT COVERS THE VIDEO
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/material/slider.dart': Failed assertion: line 166 pos 15: 'value >= min && value <= max': is not true.
The relevant error-causing widget was: 

//THE VIDEO PAUSES

The getter 'inMinutes' was called on null.
Receiver: null
Tried calling: inMinutes
The relevant error-causing widget was:

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The getter 'inSeconds' was called on null.
Receiver: null
Tried calling: inSeconds

//THE VIDEO PAUSES

I/flutter (14958): ✅ _.dataStatus DataStatus.loaded
E/ExoPlayerImplInternal(14958): Source error.
E/ExoPlayerImplInternal(14958): e.d.a.a.p0.m
E/ExoPlayerImplInternal(14958): 	at e.d.a.a.p0.i0.f.d(:288)
E/ExoPlayerImplInternal(14958): 	at e.d.a.a.p0.i0.n.f(:564)
E/ExoPlayerImplInternal(14958): 	at e.d.a.a.p0.o.f(:78)
E/ExoPlayerImplInternal(14958): 	at e.d.a.a.p0.i0.k.f(:247)
E/ExoPlayerImplInternal(14958): 	at e.d.a.a.q.d(:155)
E/ExoPlayerImplInternal(14958): 	at e.d.a.a.k.z(:1588)
E/ExoPlayerImplInternal(14958): 	at e.d.a.a.k.r(:1560)
E/ExoPlayerImplInternal(14958): 	at e.d.a.a.k.handleMessage(:321)
E/ExoPlayerImplInternal(14958): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal(14958): 	at android.os.Looper.loop(Looper.java:214)
E/ExoPlayerImplInternal(14958): 	at android.os.HandlerThread.run(HandlerThread.java:67)
I/flutter (14958): ✅ _.dataStatus DataStatus.loaded

//THE VIDEO PLAYS BUT IT CONTINUES TO MARK THE ERROR

[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Bad state: Cannot add new events after calling close
E/flutter (14958): #0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:249:24)
E/flutter (14958): #1      _RxImpl.addListener.<anonymous closure> (package:get/get_rx/src/rx_core/rx_impl.dart:147:15)
E/flutter (14958): #2      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (14958): #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (14958): #4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (14958): #5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (14958): #6      _DelayedData.perform (dart:async/stream_impl.dart:611:14)
E/flutter (14958): #7      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
E/flutter (14958): #8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
E/flutter (14958): #9      _rootRun (dart:async/zone.dart:1182:47)
E/flutter (14958): #10     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (14958): #11     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (14958): #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (14958): #13     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (14958): #14     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (14958): #15     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (14958): #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (14958): #17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (14958): #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**Comment by CarmenLexa** [comment]
I am using the latest version meedu_player 0.3.3

**Comment by the-meedu-app** [comment]
> I am playing live videos, at first it works very well but when changing video I have these errors:
> 
> //THE VIDEO PLAYS AND THEN PAUSES AND A RED COLOR BLOCK APPEARS THAT COVERS THE VIDEO
> ════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
> 'package:flutter/src/material/slider.dart': Failed assertion: line 166 pos 15: 'value >= min && value <= max': is not true.
> The relevant error-causing widget was:
> 
> //THE VIDEO PAUSES
> 
> The getter 'inMinutes' was called on null.
> Receiver: null
> Tried calling: inMinutes
> The relevant error-causing widget was:
> 
> ════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
> The getter 'inSeconds' was called on null.
> Receiver: null
> Tried calling: inSeconds
> 
> //THE VIDEO PAUSES
> 
> I/flutter (14958): ✅ _.dataStatus DataStatus.loaded
> E/ExoPlayerImplInternal(14958): Source error.
> E/ExoPlayerImplInternal(14958): e.d.a.a.p0.m
> E/ExoPlayerImplInternal(14958): at e.d.a.a.p0.i0.f.d(:288)
> E/ExoPlayerImplInternal(14958): at e.d.a.a.p0.i0.n.f(:564)
> E/ExoPlayerImplInternal(14958): at e.d.a.a.p0.o.f(:78)
> E/ExoPlayerImplInternal(14958): at e.d.a.a.p0.i0.k.f(:247)
> E/ExoPlayerImplInternal(14958): at e.d.a.a.q.d(:155)
> E/ExoPlayerImplInternal(14958): at e.d.a.a.k.z(:1588)
> E/ExoPlayerImplInternal(14958): at e.d.a.a.k.r(:1560)
> E/ExoPlayerImplInternal(14958): at e.d.a.a.k.handleMessage(:321)
> E/ExoPlayerImplInternal(14958): at android.os.Handler.dispatchMessage(Handler.java:103)
> E/ExoPlayerImplInternal(14958): at android.os.Looper.loop(Looper.java:214)
> E/ExoPlayerImplInternal(14958): at android.os.HandlerThread.run(HandlerThread.java:67)
> I/flutter (14958): ✅ _.dataStatus DataStatus.loaded
> 
> //THE VIDEO PLAYS BUT IT CONTINUES TO MARK THE ERROR
> 
> [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Bad state: Cannot add new events after calling close
> E/flutter (14958): #0 _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:249:24)
> E/flutter (14958): #1 _RxImpl.addListener. (package:get/get_rx/src/rx_core/rx_impl.dart:147:15)
> E/flutter (14958): #2 _rootRunUnary (dart:async/zone.dart:1198:47)
> E/flutter (14958): #3 _CustomZone.runUnary (dart:async/zone.dart:1100:19)
> E/flutter (14958): #4 _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
> E/flutter (14958): #5 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
> E/flutter (14958): #6 _DelayedData.perform (dart:async/stream_impl.dart:611:14)
> E/flutter (14958): #7 _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
> E/flutter (14958): #8 _PendingEvents.schedule. (dart:async/stream_impl.dart:687:7)
> E/flutter (14958): #9 _rootRun (dart:async/zone.dart:1182:47)
> E/flutter (14958): #10 _CustomZone.run (dart:async/zone.dart:1093:19)
> E/flutter (14958): #11 _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> E/flutter (14958): #12 _CustomZone.bindCallbackGuarded. (dart:async/zone.dart:1037:23)
> E/flutter (14958): #13 _rootRun (dart:async/zone.dart:1190:13)
> E/flutter (14958): #14 _CustomZone.run (dart:async/zone.dart:1093:19)
> E/flutter (14958): #15 _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> E/flutter (14958): #16 _CustomZone.bindCallbackGuarded. (dart:async/zone.dart:1037:23)
> E/flutter (14958): #17 _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
> E/flutter (14958): #18 _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

Please provide your code

**Comment by the-meedu-app** [comment]
closed by no response for the users
