### ISSUE TITLE
Allow to set widgets to customize icons for the player

### ISSUE THREAD

**Issue by gabrielginter** [the-meedu-app/flutter-meedu-player#21]
I love the work you've done on this player, I'm using it now with no issues, my only desired feature would be an option to customize the icons used for play, pause, fullscreen, etc. This could be set as properties in the MeeduPlayerController, similar to what you've done with 'bottomRight'.

Another good feature would be to add the option to disable or hide some icons completely in some situations. For example in my use case I don't always want the user to be able to go fullscreen.

If I have time after my project I might create a fork and share it.

**Comment by the-meedu-app** [comment]
> I love the work you've done on this player, I'm using it now with no issues, my only desired feature would be an option to customize the icons used for play, pause, fullscreen, etc. This could be set as properties in the MeeduPlayerController, similar to what you've done with 'bottomRight'.
> 
> Another good feature would be to add the option to disable or hide some icons completely in some situations. For example in my use case I don't always want the user to be able to go fullscreen.
> 
> If I have time after my project I might create a fork and share it.

Thanks for your feedback in this moment I can't apply these changes because I am a little busy. But I'm goin to add it to the next version

**Comment by the-meedu-app** [comment]
@gabrielginter  check the new version ^0.4.0

**Comment by gabrielginter** [comment]
@the-meedu-app thanks for the update, I tested it and it seems to be working fine, I'll ask the designer to come up with some icons. Thanks for the update!
