### ISSUE TITLE
(.m3u8) HLS Video Streaming not Support

### ISSUE THREAD

**Issue by CarmenLexa** [the-meedu-app/flutter-meedu-player#25]
I am trying to play live video with formats

# EXT-X-MEDIA
# EXT-X-STREAM-INF

but the player doesn't work it shows me an error message

**Comment by the-meedu-app** [comment]
> I am trying to play live video with formats
> 
> # EXT-X-MEDIA
> # EXT-X-STREAM-INF
> but the player doesn't work it shows me an error message

Hi @CarmenLexa  this plugin use the official video_player plugin, in this moment the video_player plugin does not support these formats please add your issue here https://github.com/flutter/flutter/issues?q=m3u8
