### ISSUE TITLE
Video player case  and full screen size 

### ISSUE THREAD

**Issue by jatin-rajput** [the-meedu-app/flutter-meedu-player#9]
Hey your plugin is awesome ..😁
But i am facing issues like

1- i want to use your player case Like  catch the duration of video  for the advertisment in between the video..

2- full screen working good but some full screen phones .. it look akward i mean your player didn't took full width in full screen phones.. 

Can u please help me... 🙏🙏

**Comment by the-meedu-app** [comment]
> Hey your plugin is awesome ..😁
> But i am facing issues like
> 
> 1- i want to use your player case Like catch the duration of video for the advertisment in between the video..
> 
> 2- full screen working good but some full screen phones .. it look akward i mean your player didn't took full width in full screen phones..
> 
> Can u please help me... 🙏🙏

Could you provide some screenshots?

**Comment by jatin-rajput** [comment]
Sir i want use logic like youtube .for Admob ads between the videos. Can you help me.

**Comment by jatin-rajput** [comment]
And sir your full screen work good. But for notch display its doesn't take full width..i hope you understand

**Comment by the-meedu-app** [comment]
> And sir your full screen work good. But for notch display its doesn't take full width..i hope you understand

The video player in full screen mode  uses SafeArea to prevent content behind the status bar that also includes the notch

**Comment by the-meedu-app** [comment]
> And sir your full screen work good. But for notch display its doesn't take full width..i hope you understand

It depends of your logic, you can put a content in the front of the video player and hide the content after de admob is finished or closed
